# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99f1b43334ef4fdef61c2f7c583b33d396825b203b6c30d144989ff711b353579379856a397f72a70094c6974074989597b6d982cfee0ab3133e51065bdacfad

test:
  secret_key_base: 9f1eb97ed18d3a2ebe35279f592890af0a3df8e653bdd8e2afd7312a07fde97b4f6a8ea75ff13a45ea687314b669b966813467fe25c72022362d0bfaf04bcd18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
